// src/components/Response/StatusBadge.tsx
import { getStatusColor } from '@/utils/http-colors';

interface StatusBadgeProps {
  status: number;
  statusText: string;
}

export const StatusBadge = ({ status, statusText }: StatusBadgeProps): React.JSX.Element => {
  const colorClass = getStatusColor(status);

  return (
    <span
      className={`font-semibold px-3 py-1.5 rounded-lg text-sm transition-colors duration-200 ${colorClass}`}
      data-testid="status-badge"
    >
      {status} {statusText}
    </span>
  );
};

// src/lib/components/Response/StatusBadge.svelte
<script lang="ts">
  import { getStatusColor } from '$lib/utils/http-colors';

  interface Props {
    /** HTTP status code */
    status: number;
    /** HTTP status text */
    statusText: string;
  }

  let { status, statusText }: Props = $props();

  // Derived
  const colorClass = $derived(getStatusColor(status));
</script>

<span
  class="font-semibold px-3 py-1.5 rounded-md text-sm transition-colors duration-200 {colorClass}"
  data-testid="status-badge"
>
  {status} {statusText}
</span>
