// src/routes/+page.svelte
<script lang="ts">
  import { executeRequest } from '$lib/api/http';
  import { createRequestParams, type HttpMethod, type HttpResponse } from '$lib/types/http';
  import MainLayout from '$lib/components/Layout/MainLayout.svelte';
  import RequestHeader from '$lib/components/Request/RequestHeader.svelte';
  import StatusBadge from '$lib/components/Response/StatusBadge.svelte';

  // State
  let url = $state('https://httpbin.org/get');
  let method = $state<HttpMethod>('GET');
  let loading = $state(false);
  let response = $state<HttpResponse | null>(null);
  let error = $state<string | null>(null);

  // Derived
  const isValidUrl = $derived(url.length > 0);

  // Handlers
  async function handleSend(): Promise<void> {
    if (!isValidUrl) return;

    loading = true;
    error = null;
    response = null;

    try {
      const params = createRequestParams(url, method);
      response = await executeRequest(params);
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  }

  function handleMethodChange(newMethod: HttpMethod): void {
    method = newMethod;
  }
</script>

<MainLayout>
  {#snippet headerContent()}
    <RequestHeader
      bind:url
      {method}
      {loading}
      onMethodChange={handleMethodChange}
      onSend={handleSend}
    />
  {/snippet}

  {#snippet requestContent()}
    <div class="h-full flex flex-col">
      {#if error}
        <div
          class="p-4 bg-destructive/10 border border-destructive/20 rounded-lg text-destructive m-4"
          role="alert"
          data-testid="error-panel"
        >
          <strong>Error:</strong>
          {error}
        </div>
      {/if}
      <div class="flex-1 p-4 text-muted-foreground">Request builder content will go here</div>
    </div>
  {/snippet}

  {#snippet responseContent()}
    <div class="h-full flex flex-col">
      {#if response}
        <div class="flex-1 flex flex-col overflow-hidden">
          <div
            class="flex justify-between items-center px-4 py-2 border-b border-border bg-muted/30"
          >
            <StatusBadge status={response.status} statusText={response.status_text} />
            <span
              class="text-muted-foreground text-sm font-mono transition-colors duration-200"
              data-testid="response-timing"
            >
              {response.timing.total_ms}ms
            </span>
          </div>

          <div class="flex-1 overflow-auto p-4 bg-card">
            <pre
              class="font-mono text-sm whitespace-pre-wrap break-words text-foreground"
              data-testid="response-body">{response.body}</pre>
          </div>
        </div>
      {:else}
        <div class="flex-1 flex items-center justify-center text-muted-foreground">
          Send a request to see the response
        </div>
      {/if}
    </div>
  {/snippet}
</MainLayout>

// src/routes/index.tsx
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { FileText, Send } from 'lucide-react';
import { executeRequest } from '@/api/http';
import { createRequestParams, type HttpMethod } from '@/types/http';
import { RequestHeader } from '@/components/Request/RequestHeader';
import { RequestBuilder } from '@/components/Request/RequestBuilder';
import { StatusBadge } from '@/components/Response/StatusBadge';
import { ResponseViewer } from '@/components/Response/ResponseViewer';
import { EmptyState } from '@/components/ui/EmptyState';
import { useRequestStore } from '@/stores/useRequestStore';
import { MainLayout } from '@/components/Layout/MainLayout';

export const HomePage = (): React.JSX.Element => {
  const { method, response, isLoading, error, setMethod, setUrl, setResponse, setLoading, setError } =
    useRequestStore();

  const [localUrl, setLocalUrl] = useState('https://httpbin.org/get');
  const [localMethod, setLocalMethod] = useState<HttpMethod>(method as HttpMethod);

  const isValidUrl = localUrl.length > 0;

  const handleSend = async (): Promise<void> => {
    if (!isValidUrl) return;

    setLoading(true);
    setError(null);
    setResponse(null);
    setUrl(localUrl);
    setMethod(localMethod);

    try {
      const params = createRequestParams(localUrl, localMethod);
      const result = await executeRequest(params);
      setResponse(result);
    } catch (e) {
      const errorMessage = e instanceof Error ? e.message : String(e);
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleMethodChange = (newMethod: HttpMethod): void => {
    setLocalMethod(newMethod);
    setMethod(newMethod);
  };

  const handleUrlChange = (newUrl: string): void => {
    setLocalUrl(newUrl);
  };

  return (
    <MainLayout
      headerContent={
        <RequestHeader
          method={localMethod}
          url={localUrl}
          loading={isLoading}
          onMethodChange={handleMethodChange}
          onUrlChange={handleUrlChange}
          onSend={handleSend}
        />
      }
      requestContent={
        <div className="h-full flex flex-col bg-bg-app">
          {error && (
            <div
              className="p-4 mx-4 mt-4 bg-signal-error/10 border border-signal-error/20 rounded-lg text-signal-error text-sm"
              role="alert"
              data-testid="error-panel"
            >
              {error}
            </div>
          )}
          <div className="flex-1 overflow-hidden">
            <RequestBuilder />
          </div>
        </div>
      }
      responseContent={
        <div className="h-full flex flex-col bg-bg-app">
          <AnimatePresence mode="wait">
            {response ? (
              <motion.div
                key="response"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.2 }}
                className="flex-1 flex flex-col overflow-hidden"
              >
                {/* Status bar */}
                <div className="flex justify-between items-center px-4 py-2 border-b border-border-subtle bg-bg-surface">
                  <StatusBadge status={response.status} statusText={response.status_text} />
                </div>

                {/* Response viewer with tabs */}
                <ResponseViewer response={response} />
              </motion.div>
            ) : (
              <motion.div
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex-1 h-full"
              >
                <EmptyState
                  title="Response will appear here"
                  description="Send a request to see the response, headers, and timing information displayed in a clear, readable format."
                  muted
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      }
    />
  );
};
