// src/lib/components/Layout/Sidebar.svelte
<script lang="ts">
  import * as Card from '$lib/components/ui/card';
  import { Folder, History } from 'lucide-svelte';
</script>

<aside
  class="w-64 h-full border-r border-border bg-muted/30 flex flex-col transition-all duration-200"
  data-testid="sidebar"
>
  <Card.Root class="flex-1 rounded-none border-0 border-r bg-transparent">
    <Card.Header class="pb-2">
      <Card.Title class="text-sm font-semibold text-foreground">Collections</Card.Title>
    </Card.Header>
    <Card.Content>
      <div
        class="flex items-center gap-2 text-sm text-muted-foreground hover:bg-muted/50 rounded px-2 py-1.5 transition-colors"
      >
        <Folder size={16} />
        <span>No collections yet</span>
      </div>
    </Card.Content>
  </Card.Root>

  <Card.Root class="flex-1 rounded-none border-0 border-r border-t bg-transparent">
    <Card.Header class="pb-2">
      <Card.Title class="text-sm font-semibold text-foreground">History</Card.Title>
    </Card.Header>
    <Card.Content>
      <div
        class="flex items-center gap-2 text-sm text-muted-foreground hover:bg-muted/50 rounded px-2 py-1.5 transition-colors"
      >
        <History size={16} />
        <span>No history yet</span>
      </div>
    </Card.Content>
  </Card.Root>
</aside>

// src/components/Layout/Sidebar.tsx
/**
 * Copyright (c) 2026 BaseState LLC
 * SPDX-License-Identifier: MIT
 */

import React, { useState } from 'react';
import { Folder, ChevronDown, ChevronRight } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { CollectionList } from '@/components/Sidebar/CollectionList';
import { containedFocusRingClasses } from '@/utils/accessibility';
import { cn } from '@/utils/cn';

interface DrawerSectionProps {
  title: string;
  icon: React.ReactNode;
  defaultOpen?: boolean;
  children: React.ReactNode;
  testId?: string;
}

const DrawerSection = ({
  title,
  icon: _icon,
  defaultOpen = true,
  children,
  testId,
}: DrawerSectionProps): React.JSX.Element => {
  // icon parameter is kept for API consistency but not currently used in the UI
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div
      className="border-b border-border-subtle last:border-b-0 flex flex-col min-h-0"
      data-test-id={testId}
    >
      <button
        type="button"
        className={cn(
          containedFocusRingClasses,
          'w-full flex items-center gap-2 px-4 py-3 hover:bg-bg-raised/30 transition-colors cursor-pointer group'
        )}
        onClick={() => {
          setIsOpen(!isOpen);
        }}
        aria-expanded={isOpen}
        data-test-id={testId !== undefined ? `${testId}-toggle` : undefined}
      >
        <span className="text-text-muted group-hover:text-text-primary transition-colors">
          {isOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
        </span>
        <span
          className="text-xs font-semibold text-text-secondary uppercase tracking-wider group-hover:text-text-primary transition-colors"
          data-test-id={testId !== undefined ? `${testId}-title` : undefined}
        >
          {title}
        </span>
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2, ease: 'easeInOut' }}
            className="flex-1 min-h-0"
          >
            <div
              className="px-3 pb-3 h-full overflow-y-auto overflow-x-hidden"
              data-scroll-container
            >
              {children}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export const Sidebar = (): React.JSX.Element => {
  return (
    <aside className="w-full h-full bg-bg-surface flex flex-col" data-test-id="sidebar-content">
      <div className="flex-1 min-h-0">
        <DrawerSection
          title="Collections"
          icon={<Folder size={14} />}
          defaultOpen
          testId="collections-drawer"
        >
          <CollectionList />
        </DrawerSection>
      </div>
    </aside>
  );
};
